language: node_js
node_js:
  - "stable"
script:
  - echo "skipping build"
deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_AUTH
  message: "${TRAVIS_BRANCH} ${TRAVIS_COMMIT} ${TRAVIS_PULL_REQUEST} ${TRAVIS_COMMIT_MESSAGE}"
  on:
    all_branches: true
